//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string DNI { get; set; }
        public string Posswere { get; set; }
        public string PerilID { get; set; }
    
        public virtual Perfiles Perfil { get; set; }
    }
}
